implement invoicePaymentDefinition
cafetamine/wsei-InvoiceManagmentStudio pull request #11
Opened 2019-11-16 19:42 UTC by MaciejBesaraba

2019-11-18 08:16 UTC, cafetamine requested changes
Please fallow comments to specific files.

Also remeber to check out to this branch before you start to work on this review.
Also great job! Don't be discouraged, I am just a little on picky side : D

2019-11-18 08:16 UTC, cafetamine commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        EPaymentType PaymentType { get; }
1. EPaymentType was not implemented. It is still your job! : )
    - create file `EPaymentType.cs` in same package as `IInvoicePaymentDefinition`, use [enum ESex](https://github.com/arekbystrowicz/wsei-InvoiceManagmentStudio/blob/core/InvoiceManagementStudio/Core/Definition/Entity/ESex.cs) as reference.
    - Consider values such as `Cash`, `CreditCard`, `BankTransfer` etc.
    - Remember to add this values to uml as well

2. Use flat property accessors - instead of `PaymentType` simple `Type` is sufficient.
    ```csharp
    IInvoicePayment payment = new Payment();
    payment.Type
    ```
    Is simpler and as descriptive as
    ```csharp
    payment.PaymentType
    ```

2019-11-18 08:16 UTC, cafetamine commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string LocalTime { get; }
Change name of this field to `TimeZone`, and use c sharp standart library type for it - `TimeZoneInfo`.
```csharp
TimeZoneInfo TimeZone { get; }
```

2019-11-18 08:16 UTC, cafetamine commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        decimal PaymentAmount { get; }
Payment prefix is not neccessery (same as with PaymentType).

2019-11-18 08:16 UTC, cafetamine commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string CreditCardType { get; }
Not every payment is done with CreditCard so this field is not universal for each payment object.
It is a bit of hard nut to swallow but for now just add different credit card types to enum `EPaymentType` eg.
- CardVisa,
- CardMaestro,
- CardAmericanExperss

Try to draw a region around a specific group - eg.
```csharp
public enum EPaymentType
{
    ...
    Cash,

    #region BankCards
    CardVisa,
    CardMestro,
    ...
    #endregion
    
    ...
}
```

2019-11-18 08:16 UTC, arekbystrowicz commented on Documentation/Diagrams/UML-Model/ivms-model-uml-source.drawio
> +<mxfile host="www.draw.io" modified="2019-11-16T17:01:15.835Z" agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" etag="tL5Zdrm2
Remeber to udpate this file after resolving other comments from this review.
Also try to keep consistent styling in this file - you missed spaces there and there. Also one of properites does not have `+` in front of it.

The plus sign is a symbol representing data access modifier in uml.
- `+` means `public`
- `-` means `private`
So it is really important : )

2019-11-19 07:48 UTC, cafetamine commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string LocalTime { get; }
Naming is important. You want to know as mutch about a variable as you can simply by looking at it in code.

If i would see such call in code:
```csharp
var pymentTimeZone = payment.LocalTime;
```
I would guess it is a DateTime type.

But when i see:
```csharp
var paymentTimeZone = payment.TimeZone;
```
I know right away what it represents.

2019-11-21 13:39 UTC, arekbystrowicz commented on Documentation/Diagrams/UML-Model/ivms-model-uml-source.drawio
> +<mxfile host="www.draw.io" modified="2019-11-16T17:01:15.835Z" agent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36" etag="tL5Zdrm2
(and delete this field)

2019-12-06 16:59 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        EPaymentType PaymentType { get; }
Requested changes added to invoicePayment branch

2019-12-06 17:13 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string LocalTime { get; }
Gotcha, will remember about this.

2019-12-06 17:13 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        decimal PaymentAmount { get; }
Changed.

2019-12-06 17:13 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string CreditCardType { get; }
Region added, please check if it's implemented correctly.

2019-12-07 09:56 UTC, arekbystrowicz commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string CreditCardType { get; }
Enum is all bueno.
Please delete property CreditCardType compeately

2019-12-07 09:59 UTC, arekbystrowicz commented on InvoiceManagementStudio/Core/Definition/Payment/IInvoicePaymentDefinition.cs
> +        string CreditCardType { get; }
Please delete CreditCardType property compleatly after implementing enum.

2019-12-07 10:00 UTC, cafetamine requested changes
Please delete property CreditCardType compleately.

2019-12-09 16:34 UTC, cafetamine approved these changes

2019-12-09 16:34 UTC, merged