add InvoiceItem class
cafetamine/wsei-InvoiceManagmentStudio pull request #18
Opened 2019-12-09 19:38 UTC by MaciejBesaraba

Implement InvoiceItem class data model, please review.

2019-12-10 08:04 UTC, cafetamine requested changes
1. Please think through `Subtotal` and `Total` properties, added explanatory descriptions. In case I'm wrong write in conversation regarding them.

1. Please fallow code style comments regarding unnecesary blank lines.

1. Next time try to add more commits for your objects. My flow would look somewhat like:
    - add auto properties
    - implement required arguments constructor
    - implement properties
    - implement IEqutable interface
    - implement ToString

    and regarding this review changes:
    - delete unnecessary balnk spaces
    - fix properties Total and Subtotal

1. Remeber that you don't have to create a seperate pull request for result of your work on this review. After implementing neccessary changes just push your branch (`invoiceItem`) to origin.

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> 2 blank lines between auto properties and constructors

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> delete blank lines

```c#
public InvoiceItem(
    IObjectIdentifier<ulong> id,
    string name,
    decimal unitPrice,
    EUnitType unitType,
    decimal discount,
    double quantity
)
{
    Id = id;
    Name = name;
    UnitPrice = unitPrice;
    UnitType = unitType;
    Discount = discount;
    Quantity = quantity;
}
```

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> 2 blank lines between constructors and properties

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +        public decimal Total => UnitPrice - Discount;
`Discount` is considered as full discount on all items undependent of `UnitPrice` and `Quanitity`.
`Total` is a full price payed for aggregated value of this item set. You should include `Quantity` here.

Item of price 2.50 with quantity of 2 and no discount should result in Total = 5.00
Item of price 2.50 with quantity of 2 and discount of 1 should result in Total = 4.00

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +        public decimal Subtotal => Total * Quantity;
Subtotal is a `Total` (above conversation), but it does not include `Discount`.

Item of price 2.50 with quantity of 2 and no discount should result in Subotal = 5.00
Item of price 2.50 with quantity of 2 and discount of 1 should result in Subotal = 5.00

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> 2 blank lines

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> no blank lines between "`{`" and "`return`"

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> delete blank line

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +            // TODO ArBy redemptionDate equality
`// TODO ...` is a comment with a tag meaning `to do later` you probaly shoud not leave todo tags for me.
And this one is not valid here so delete it.

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> delete blank line

2019-12-10 08:04 UTC, cafetamine commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Code style -> single blank line before return statement in bigger batch

2019-12-12 12:00 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:00 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:00 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:01 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +        public decimal Total => UnitPrice - Discount;
Not sure if know what you mean. As far as im concerned, Total should include UnitPrice multiplied by Quantity, right?

2019-12-12 12:01 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +        public decimal Subtotal => Total * Quantity;
Fixed. Please review.

2019-12-12 12:02 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:02 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:03 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +            // TODO ArBy redemptionDate equality
Sorry, just forget to delete it.

2019-12-12 12:03 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:03 UTC, MaciejBesaraba commented on InvoiceManagementStudio/Model/Domain/InvoiceItem.cs
> +
Fixed.

2019-12-12 12:52 UTC, cafetamine approved these changes

2019-12-12 12:53 UTC, merged